### ISSUE TITLE
Edge compatibility

### ISSUE THREAD

**Issue by ruerob** [umanghome/swipe-listener#22] opened 2019-07-08 11:41 UTC
Hey there!

I used your package with big satisfaction in my meteor.js project until I tried to get it working in a Microsoft Edge browser.

Edge still doesn't understand spread syntax in object literals. So the line 42 in your index.js throws an error.

**Comment by umanghome** [comment] 2019-07-08 15:17
Thanks for reporting. I'll be looking at resolving IE and Edge issues, since one was also reported at #18.

I see the spread operator is being used in `index.js`, but I've recently merged a PR making a minified and transpiled version as the default entry-point for the app (#20), which might solve the issue. I'll test it nevertheless and add any fixes required before publishing the next version.

**Comment by umanghome** [comment] 2019-07-08 15:37
Confirmed that using the files in `dist/` works in IE.

**Closed by umanghome** 2019-07-08 15:37 UTC

**Comment by umanghome** [comment] 2019-07-08 15:56
Fixed in `v1.1.0`

**Comment by ruerob** [comment] 2019-07-09 07:12
Whoa! Thank you for the fast fix! :0D That's awesome!
